[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32WLE5JCIx --connect-under-reset"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "linker=flip-link"
]

[build]
target = "thumbv7em-none-eabi"
